-- Add new enhancements to the wallet table without dropping existing ones

ALTER TABLE wallet ADD COLUMN IF NOT EXISTS currency VARCHAR(3) NOT NULL DEFAULT 'USD';
ALTER TABLE wallet ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE wallet ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE wallet ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
